In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [20]:
def Gaussian_1D_hankel(n):
    moments = np.array([(1**(r+1) - (-1)**(r+1)) / (r + 1) for r in range(2 * n)])
    M = np.array([moments[i:i+n] for i in range(n)])
    b = moments[n:]
    coef = np.linalg.solve(M, b)
    nodes = np.roots(np.insert(np.flip(-coef),0,1))
    V = np.array([nodes**i for i in range(n)])
    weights = np.linalg.solve(V , moments[:n])
    return nodes,weights

In [27]:
n = 6
real_n , real_w = np.polynomial.legendre.leggauss(n)
n , w = Gaussian_1D_hankel(n)
real_n , n , real_w , w


(array([-0.93246951, -0.66120939, -0.23861919,  0.23861919,  0.66120939,
         0.93246951]),
 array([-0.93246951, -0.66120939,  0.93246951,  0.66120939, -0.23861919,
         0.23861919]),
 array([0.17132449, 0.36076157, 0.46791393, 0.46791393, 0.36076157,
        0.17132449]),
 array([0.17132449, 0.36076157, 0.17132449, 0.36076157, 0.46791393,
        0.46791393]))

In [25]:
n = 60
real_n , real_w = np.polynomial.legendre.leggauss(n)
n , w = Gaussian_1D_hankel(n)
real_n , n

(array([-0.99921012, -0.99584053, -0.9897879 , -0.9810672 , -0.96970179,
        -0.95572226, -0.93916628, -0.92007848, -0.89851031, -0.87451992,
        -0.84817198, -0.81953753, -0.78869374, -0.75572378, -0.72071651,
        -0.68376633, -0.64497283, -0.6044406 , -0.5622789 , -0.5186014 ,
        -0.47352584, -0.42717374, -0.37967006, -0.33114285, -0.28172294,
        -0.23154355, -0.18073996, -0.12944914, -0.07780933, -0.02595977,
         0.02595977,  0.07780933,  0.12944914,  0.18073996,  0.23154355,
         0.28172294,  0.33114285,  0.37967006,  0.42717374,  0.47352584,
         0.5186014 ,  0.5622789 ,  0.6044406 ,  0.64497283,  0.68376633,
         0.72071651,  0.75572378,  0.78869374,  0.81953753,  0.84817198,
         0.87451992,  0.89851031,  0.92007848,  0.93916628,  0.95572226,
         0.96970179,  0.9810672 ,  0.9897879 ,  0.99584053,  0.99921012]),
 array([-2.03664735+0.j        , -1.74026476+0.j        ,
         2.03664735+0.j        ,  1.74026476+0.j        ,
      