In [9]:
import numpy as np
from numpy.polynomial import Polynomial as P
from numpy.polynomial import chebyshev as c
from numpy.polynomial import Chebyshev as C
from numpy.polynomial import Legendre as L
from math import factorial as fac

In [ ]:
inte_p = lambda p,a,b: p.integ()(b) - p.integ()(a)
def Gaussian_1D_hankel(n):
    

    # moments = np.array([(1**(r+1) - (-1)**(r+1)) / (r+1) for r in range(2 * n)])
    # moments = np.array([inte_p(L.basis(r) , -1 , 1) for r in range(2 * n)])
    # part_1 = lambda k: np.array([(-1)**(s + n) * fac(k) * 2 / (fac(s) * fac(k - s) * (s + n + 1))  for s in range(k)]).sum()
    # part_2 = lambda m: np.array([(-2)**k * fac(m + k - 1) * part_1(k) / (fac(m - k) * (fac(2 * k))) for k in range(m)]).sum()
    # b = np.array([part_2(m) for m in range(n)])
    Lam = lambda n: ((-1)**n + 1)/(1 - n**2) if n != 1 else 0
    moments = np.array([Lam(r)  for r in range(2 * n)])
    # I = np.eye(n)
    # _I = np.fliplr(I)
    # M1 = np.array([[(moments[i+j] )  for i in range(n)] for j in range(n)])
    # M2 = np.array([[(moments[abs(i-j)])  for i in range(n)] for j in range(n)]) 
    # print(M1,M1@_I,M2,sep='\n')
    
    ## C_mC_n = (C_{m+n} + C{|m-n|}) / 2
    M = np.array([[(moments[i+j] + moments[abs(i-j)])  for i in range(n)] for j in range(n)])
    

    b = np.array([(moments[i+n] + moments[abs(i-n)])  for i in range(n)])
    coef = np.linalg.solve(M, b)
    new_coef = np.concatenate([-coef, [1]])
    nodes = C(new_coef).roots() 
    V = np.array([C.basis(i)(nodes) for i in range(n)])
    weights = np.linalg.solve(V , moments[:n])
    return nodes,weights

In [29]:
n = 5
real_n , real_w = np.polynomial.legendre.leggauss(n)
nodes , w  = Gaussian_1D_hankel(n)
max(abs(real_n - nodes )), max(abs(real_w - w))

[[ 2.          0.         -0.66666667 -0.         -0.13333333]
 [ 0.         -0.66666667 -0.         -0.13333333 -0.        ]
 [-0.66666667 -0.         -0.13333333 -0.         -0.05714286]
 [-0.         -0.13333333 -0.         -0.05714286 -0.        ]
 [-0.13333333 -0.         -0.05714286 -0.         -0.03174603]]
[[-0.13333333  0.         -0.66666667  0.          2.        ]
 [ 0.         -0.13333333  0.         -0.66666667  0.        ]
 [-0.05714286  0.         -0.13333333  0.         -0.66666667]
 [ 0.         -0.05714286  0.         -0.13333333  0.        ]
 [-0.03174603  0.         -0.05714286  0.         -0.13333333]]
[[ 2.          0.         -0.66666667 -0.         -0.13333333]
 [ 0.          2.          0.         -0.66666667 -0.        ]
 [-0.66666667  0.          2.          0.         -0.66666667]
 [-0.         -0.66666667  0.          2.          0.        ]
 [-0.13333333 -0.         -0.66666667  0.          2.        ]]


(1.1102230246251565e-15, 7.494005416219807e-16)