In [1]:
import numpy as np
from numpy.polynomial import Polynomial as P
from numpy.polynomial import chebyshev as c
from numpy.polynomial import Chebyshev as C
from numpy.polynomial import Legendre as L
from math import factorial as fac

In [ ]:
inte_p = lambda p,a,b: p.integ()(b) - p.integ()(a)
def Gaussian_1D_hankel(n):
    

    # moments = np.array([(1**(r+1) - (-1)**(r+1)) / (r+1) for r in range(2 * n)])
    # moments = np.array([inte_p(L.basis(r) , -1 , 1) for r in range(2 * n)])
    # part_1 = lambda k: np.array([(-1)**(s + n) * fac(k) * 2 / (fac(s) * fac(k - s) * (s + n + 1))  for s in range(k)]).sum()
    # part_2 = lambda m: np.array([(-2)**k * fac(m + k - 1) * part_1(k) / (fac(m - k) * (fac(2 * k))) for k in range(m)]).sum()
    # b = np.array([part_2(m) for m in range(n)])

    moments = np.array([inte_p(C.basis(r) , -1 , 1) for r in range(2 * n)])
    ## C_mC_n = C_{m+n} + C{|m-n|}
    M = np.array([[moments[i+j] + moments[abs(i-j)] for i in range(n)] for j in range(n)])
    

    b = np.array([moments[i+n] + moments[abs(i-n)] for i in range(n)])
    coef = np.linalg.solve(M, b)
    new_coef = c.cheb2poly(coef)
    nodes = P(np.append(-new_coef, [0.0,1.0])).roots() # Add an extra zero since b[-1]=0
    V = np.array([C.basis(i)(nodes) for i in range(n)])
    weights = np.linalg.solve(V , moments[:n])
    return nodes,weights

In [3]:
n = 3
real_n , real_w = np.polynomial.legendre.leggauss(n)
nodes , w  = Gaussian_1D_hankel(n)
real_n , nodes , real_w , w

0.0


(array([-0.77459667,  0.        ,  0.77459667]),
 array([0.-0.77459667j, 0.+0.j        , 0.+0.77459667j]),
 array([0.55555556, 0.88888889, 0.55555556]),
 array([-0.55555556-0.j,  3.11111111+0.j, -0.55555556-0.j]))